Week3
ashwanthdurairaj/pff pull request #3
Opened 2024-03-28 18:34 UTC by ashwanthdurairaj

Create week 3 assignment for review

2024-04-05 07:32 UTC, DonBrowny requested changes
Convert this project from npm to yarn. Also try adding prettier package to this repo and modify your VS code to use  prettier

2024-04-05 07:32 UTC, DonBrowny commented on week3/src/App.js
> +function Square({value, onSquareClick})
create a file names `square.jsx` and move the Squarer component code to it.

2024-04-05 07:32 UTC, DonBrowny commented on week3/src/App.js
> +function Board({xIsNext, squares, onPlay})
create a file names `board.jsx` and move the Squarer component code to it.

2024-04-05 07:32 UTC, DonBrowny commented on week3/src/App.js
> +function calculateWinner(squares) {
create a file names `utile/calculate-winner.js` and move the calcaulteWinner function to the new file.

2024-04-08 14:18 UTC, ashwanthdurairaj commented
converted project from npm to yarn, added prettier to the existing project, moved all components into a separate component folder and functions into a separate utils folder

2024-05-07 05:10 UTC, DonBrowny approved these changes

2024-05-07 09:42 UTC, merged